### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-upgrader#133]
@maxime-rainville might be the best person to look at this - there's a test failing in identifying that recipe-collaboration can be substituted for inline requirements:

https://travis-ci.org/silverstripe/silverstripe-upgrader/jobs/428652380#L606-L612

I had a quick go at updating some constraints locally but it didn't get the tests passing =/

**Comment by sminnee** [comment]
There's a couple of ways you can approach this @maxime-rainville:

 * Update your test so that it's working solely with tagged versions of those remote dependencies, which are sufficiently unlikely to change
 * Build some extra composer packages that exist solely for the purpose of testing. This is more work / cruft, so I'd probably only do that if the first approach failed.

**Comment by maxime-rainville** [comment]
The test that fails is the one that tries to convert a set of dependency to an equivalent recipe. That part of the upgrader was specifically design to be relatively liberal so it would not get bugged down in version constraint. Unfortunately that also makes it really hard to force composer to only look at specific tags.

For a while, I considered trying to pre-load the composer cache to try to foul composer into thinking it already knew all it needed to know about the package.

I think building a fake recipe and referencing it as a VCS is probably the most straight forward way of getting that test to work all the time.

**Comment by robbieaverill** [comment]
Fixed in #138 - thanks!
