### ISSUE TITLE
Composer upgrade helper

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-upgrader#45]
# Overview

In order to use this upgrader, you need to run the project on an SS4 codebase already (to get `.upgrade.yml` definitions). That's causing a bit of a chicken and egg scenario, particularly with the new inspection rules. You don't know how hard the upgrade will be (by running inspection rules), and you need to do part of the upgrade to even find out.

# Acceptance Criteria

 * Take target release as a `silverstripe/recipe-core` version constrain as a command-line argument
 * Rewrite existing core composer dependencies (e.g. `silverstripe/framework`) to `~4.0`
 * Add new dependencies based on already installed ones (e.g. add `silverstripe/admin` only when `silverstripe/cms` is installed)
 * Error out if `silverstripe/framework` already runs on a `4.x` constraint (to avoid accidentally overriding or downgrading)
 * Base dependency versions on `silverstripe/recipe-core` and `silverstripe/recipe-cms`
 * Warn when using custom composer repos (base on repo urls, e.g. if a repo path contains `silverstripe-framework`, assume it contains a fork for that module)
 * If a module doesn't have a stable release tag, error out (with standard composer errors)
 * Ignores wrongly stated `>=3.2.0` composer constraints (used to be common in SilverStripe ecosystem)
 * Works with upgrading the CWP 1.x to CWP 2.x recipe

# Notes

 * @robbieaverill made a start on this through https://gist.github.com/robbieaverill/cad0260414226645b404c45b2059fdf9
 * Track under ORB-157

# Pull Request
* [ ] #67

**Comment by chillu** [comment]
Removed ACs after talking to team:

 * If a module doesn't have a stable release tag, but a compatible pre-release branch, use it instead (but add a warning). Set `minimum-stability: dev` and `prefer-stable: true` in this case. Allow opt-out of this behaviour via a command line argument
 * If a module doesn't have a compatible stable tag or pre-release branch, remove it from the requirements and add a warning ("you'll need to add this back")
 * Allow preview mode which outputs compatible/incompatible modules instead of triggering composer updates

**Comment by maxime-rainville** [comment]
# Proposed signature
```bash
upgrader recompose  [--root-dir=ROOT-DIR] [--write] [--composer-path=composer] <recipe-core-target>
```

# What the command does
Rewrites an SS3 `composer.json` file to use SS4 dependencies.

`recipe-core-target` corresponds to a sem-ver constraint on `silverstripe/recipe-core`. Let’s say you wanted to upgrade to SS4.0, recipe-core-target would need to be `1.0`. If you want to upgrade to SS4.1,  recipe-core-target would need to be `1.1`.

At the end of the process, you may or may not have a conflict-free composer file.

# Pre-condition for the command to do anything
* User needs composer installed on their system. If `composer` or `composer.phar` is in your path, you’re sweet. Otherwise you need to specify `--composer-path` so we know where we can fin composer.
* User needs to have a `composer.json` in `root-dir`
  * That composer file minimally needs to have a (explicit?) dependency for "silverstripe/framework:3.*"

If any of the pre-conditions are not met, we bail.

# Process

## Step 1 - Loop through all the dependencies in composer one-by-one

* If it’s not a `silverstripe-module`, don’t touch it.
* If it’s referenced via a custom VCS, skip it with a nasty warning.
* If it’s a dependency tracked in recipe-core or recipe-cms, use the exact version define in the recipe.
* Otherwise, try to find the most recent version that is compatible with our targeted SS4 version.
  * If we can’t find one, skip with with warning.
  * If we can find one, update that dependency in the composer file accordingly.

## Step 2 - Show the difference
We display the difference between the original `composer.json` and the updated one.

## Step 3 -Writing changes
If the command is called with the --write flag, the change will be written and we'll try to trigger a composer update.

## Run a Composer update.
Basically we ask composer to try to find matches for our new dependencies.

At the end of the process, it’s the responsibility of the user to resolve any conflict.

# Questions

* Not sure what the point of _Add new dependencies based on already installed ones_. Let’s take the `silverstripe/cms` example: `silverstripe/admin` is already a dependency of `silverstripe/cms` … what would be the point of explicitly saying in our composer.json file that we need `silverstripe/admin`?
* Would it make sense to move people over to the recipes? 
  * So if you start off with `silverstripe/cms` in your dependencies, we add `silverstripe/recipe-cms` instead and remove any entries that are already covered by the recipe?
  * Otherwise, we add `silverstripe/recipe-core` and remove `silverstripe/framework`.
* Do I need to worry about the `silverstripe/cwp` and `silverstripe/cwp-core` package at this stage? Should I have some special rules for them?

# Possible package to add to the upgrader
* https://github.com/teqneers/PHP-Stream-Wrapper-for-Git
* https://github.com/composer/semver 
* https://github.com/justinrainbow/json-schema 
* https://github.com/Seldaek/jsonlint

**Comment by chillu** [comment]
> Not sure what the point of Add new dependencies based on already installed ones. Let’s take the silverstripe/cms example: silverstripe/admin is already a dependency of silverstripe/cms … what would be the point of explicitly saying in our composer.json file that we need silverstripe/admin?

I think it's relevant for upgrading the CWP recipe, which changed how modules are packaged in recipes. That's probably worth mentioning: A major beneficiary of this work will be CWP agencies, who are yet to upgrade to SS4. I'll add an AC around that: "Works with upgrading the CWP 1.x to CWP 2.x recipe". Is that within scope, or needs extra points?

> Would it make sense to move people over to the recipes? 

Yes, please. But only where that change wouldn't add modules that aren't mandatory. For example, a dependency on `silverstripe/cms` should be upgraded to `silverstripe/recipe-cms`, which includes `silverstripe/campaign-admin` as a new feature - that's fine. 

But: If you have added `silverstripe/taxonomy` to your project (instead of `cwp/recipe-core` or something), then we shouldn't add `silverstripe/recipe-authoring-tools` which includes `silverstripe/taxonomy`, but also a lot of other stuff.

**Comment by maxime-rainville** [comment]
# Adding new dependencies based on existing one
@chillu  I think I see where you are going with this.

Let's say I have package `silverstripe/x`:
* `silverstripe/x` version 1.0 supports SS3 and doesn't have any dependencies.
* `silverstripe/x` version 2.0 supports SS4 and now has a dependency on `silverstripe/y:^1.0`.

Because CWP is more strict on its version requirements, we don't want people to be implicitly upgraded to a more recent minor release of `silverstripe/y` 8

So if we use the upgrader to update a CWP recipe that relies on version 1.0 of `silverstripe/x`, we want to lock down a specific version of `silverstripe/x` and `silverstripe/y`.

How about we add a strict mode and a flexible mode. Strict mode would not allow you to automatically upgrade to new minor release and would add explicit version requirements for any [commercially supported packages](https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/).

## Input SS3 composer file
```json
{
    "require": {
        "silverstripe/x": "~1.0"
    }
}
```

## Output SS4 composer file with strict mode
```json
{
    "require": {
        "silverstripe/x": "~2.0.0",
        "silverstripe/y": "~1.0.5"
    }
}
```

`silverstripe/y:1.0.5` is the most recent version when the upgrader is run. If `silverstripe/y:1.1.0` and `silverstripe/y:1.0.6` gets release a week later and you run a composer update, you'll be updated to 1.0.6, but not 1.1.0.

## Output SS4 composer file with flexible mode
```json
{
    "require": {
        "silverstripe/x": "^2.0.0"
    }
}
```

`silverstripe/y:1.0.5` will be installed implicitly after running the upgrader because it's a dependency of `silverstripe/x:2.0.0`. If `silverstripe/y:1.1.0` and `silverstripe/y:1.0.6` gets release a week later and you run a composer update, you'll be updated directly to 1.1.0.

# Moving from legacy package to recipe
The simple way of doing this could be to just look at `recipe-cms` and `recipe-core` and not worry about the other recipes.

Alternatively, we could look at what dependency you have and try to find a recipe (or combination) that is completely covered but what you have. e.g.: Let's say you have `sharedraftcontent`, `contentreview`, `advancedworkflow` and `cms` ... you are effectively using the `collaboration` recipe, so we swap out those entries for `silverstripe/recipe-collaboration`.

Solution 2 sounds more fun and entertaining for me, but will probably take a bit more time.

**Comment by chillu** [comment]
We want to make it very easy to move from CWP's 1.x dependencies (https://github.com/silverstripe/cwp-installer/blob/1.8.1/composer.json) to CWP's 2.x dependencies (https://github.com/silverstripe/cwp-installer/blob/2.0.0-rc1/composer.json).

We should instruct composer to use stable releases (tags). If you install `"cwp/cwp-recipe-core@2.0.0", presumably you'll get strict tags for any modules included in that recipe as well - so no danger of getting a newer module version. 

Can you please also amend the CWP upgrading guide with using this tool as a preferred mechanism? https://www.cwp.govt.nz/developer-docs/en/2/releases_and_changelogs/cwp_recipe_basic_2.0.0/

> Alternatively, we could look at what dependencies you have and try to find a recipe (or combination) that is completely covered but what you have. e.g.: Let's say you have sharedraftcontent, contentreview, advancedworkflow and cms ... you are effectively using the collaboration recipe, so we swap out those entries for silverstripe/recipe-collaboration.

Yes, that's what I had in mind. If it's too hard, I'm fine with just replacing the CWP recipes as described in the upgrade guide above.

**Comment by tractorcow** [comment]
My suggestion is, instead of "Adding new dependencies based on existing one", is "adding new recipes based on a provided base recipe". Because you cannot ALWAYS infer "target" recipe based on the 3.x equivalent, it's probably necessary for the upgrader to provide a specific baseline recipe and version.

E.g.

```
upgrade-code recipe cwp/cwp-installer 2.0.0-rc1
```

Will use the base recipe in `cwp/cwp-installer` as the preferred set of target dependencies.

In the example above by @maxime-rainville , what is more likely is "silverstripe/y" is only recently created, and depends on "silverstripe/x" which exists in multiple versions and requires upgrade. Because the dependency is inverted, the scope of what you are really upgrading isn't "modules that silverstripe/x depend on" but rather "modules that depend on silverstripe/x", which in reality is a huge set of possible modules. Thus the need to provide a baseline source set to search within.
