### ISSUE TITLE
Upgrader adds namespace decleration to Page.php and PageController.php

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-upgrader#49]
According to https://docs.silverstripe.org/en/4/upgrading/ "The Page and PageController classes must be defined in the global namespace"

Running "~/.config/composer/vendor/bin/upgrade-code add-namespace "OurCo\NAME" NAME/mysite/code/ --write"

Puts Page and PageController into namespaces

**Comment by robbieaverill** [comment]
@worikgh that's correct, since you're asking the tool to add OurCo\NAME as the namespace to everything in `mysite/code`. I think this ties into the questions raised around PSR-4 and the Page and PageController files being in a PSR-4 autoloaded location without a namespace being incorrect anyway, but it doesn't matter to SilverStripe framework at this point - will do in future.

You could always define a PSR-0 autoloader definition in your composer.json to point to Page and PageController in say the "code" folder or anything else e.g. "legacy" then use `src/*` as your PSR-4 compatible namespaced folders.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-upgrader/pull/57

`Page`, `PageController` and `Page_Controller` are now ignored by add-namespace command.
