### ISSUE TITLE
Upgrader should put .upgrade.yml into vendorised module folder

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-upgrader#53]
Say I have a module in `vendor/monkey/bar` and I want to add "Monkey\Bar\Foo" to `vendor/monkey/bar/src/Foo`, I'd run this from my project:

```
upgrade-code add-namespace "Monkey\Bar\Foo" vendor/monkey/bar/src/Foo --write
```

This will create an .upgrade.yml file at `vendor/.upgrade.yml` which is incorrect.

It looks like the rules are "create .upgrade.yml file in the folder above the current working directory" which would have worked as expected when running this without vendorised modules.

Perhaps we need to add an argument to customise the directory that the .upgrade.yml is written to?

**Comment by robbieaverill** [comment]
Adjusted title since this isn't relevant for mysite

**Comment by NightJar** [comment]
One can work around this by running from the vendors' folder (not to be confused with the vendor folder). But ideally it should work anywhere. Besides, even after generating a `.upgrade.yml` in the correct place, running `upgrade` will then not work (see #54 )

i.e.
`cd vendor/silverstripe`
`upgrade-code add-namespace 'SilverStripe\ExternalLinks\Controllers' externallinks/src/Controllers`
Will work more as expected, since the target module root folder is an immediate child of the current one.

**Comment by tractorcow** [comment]
This will be fixed with https://github.com/silverstripe/silverstripe-upgrader/pull/57
