### ISSUE TITLE
Rewrite "extends Object"

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-upgrader#71]
Sorry for all the issues... I hope it is not too annoying.

I was wondering if some of the standard replacements could be added using some basic regex ... e.g.

https://docs.silverstripe.org/en/4/changelogs/4.0.0/#object-replace

replace:
```php

class AnyClass extends Object
```
with:

```php
use SilverStripe\Core\Extensible;
use SilverStripe\Core\Injector\Injectable;
use SilverStripe\Core\Config\Configurable;
class AnyClass
{
    use Extensible;
    use Injectable;
    use Configurable;
}
```

# Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-upgrader/pull/157 visitor that makes the replacements
- [x] ~https://github.com/silverstripe/silverstripe-framework/pull/8799 adding to `.upgrade.yml`~
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/8807

**Comment by robbieaverill** [comment]
The example you give with `extends Object` should not necessarily be replaced with the traits in your example. While they will provide the full set of functionality that Object provided, one of the drivers of splitting up this functionality is that you should use the traits that your code actually needs, rather than getting more than it needs.

It is feasible to suggest that the upgrader might be able to analyse a class and say whether it has `$this->extend()` calls (in which case apply Extensible), `Config::inst()->get(AnyClass::class)` (or variations of) calls (in which case apply Configurable and upgrade to use `$this->config()` or `static::config()`, and scan a full project to find any implementations of `AnyClass::create()` or `AnyClass::singleton()` in which case apply Injectable - this would be a fair amount of work though =)

We're using an AST parser rather than regex BTW.

**Comment by sunnysideup** [comment]
Thank you for your reply Robbie. 

I hear you on the "only apply the traits you need", but I would see these upgrade tasks more as "simplest way" forward rather than the "most correct" way forward.  The upgrade tasks would be optional (run if you deem it useful) and people can review the outcome using `-vvv` and then choose to enhance / refine where needed.  

Great about the AST parser also.

**Comment by robbieaverill** [comment]
True - what about if it also added a PHPDoc block like `/** @todo determine which of these traits are actually required */` so you could go back to it?

**Comment by sunnysideup** [comment]
To do docblock is perfect.

**Comment by chillu** [comment]
Agree with @sunnysideup on making the upgrade a good baseline. And it looks like extending object is common enough to warrant some automation.

**Comment by sunnysideup** [comment]
Can anyone give me any hints on how to write a straight replacement - as detailed in the first comment?  I'd love to write it.

_Backround_

Am I right to look at: https://github.com/silverstripe/silverstripe-upgrader/blob/master/src/UpgradeRule/PHP/RenameTranslateKeys.php as a template for a simple replacement class? Do I need to manually add it or will it run automatically because it extends `PHPUpgradeRule`. I have no idea on this module works, AST, etc... and there does not seem any documentation. Of course I can find out, but any help would be appreciated. 

We are going to try to upgrade all our client and OS modules at the same time using as much automation as possible.  If the automation is smooth enough, we could even fork all the remaining third-party SS3 modules still out there and create a upgrade-to-4 pull request for them (fully automated).  Right now, I have no idea how "automated" we can get (I may be dreaming), but it would be awesome if we could achieve that.  Obviously our goal for this is "works with SS4" NOT "is optimised for SS4".

**Comment by maxime-rainville** [comment]
@sunnysideup 

The best way to do this would probably to write a new `NodeVistor`.

You might be able to get away and add it `SilverStripe\Upgrader\UpgradeRule\PHP\RenameClasses`.

Otherwise, you'll need to create a new `PHPUpgradeRule` to reference your new node visitor and add it to `SilverStripe\Upgrader\Console\UpgradeCommand::getRules()`.

If you are really keen on trying to do this, I'd be happy to give you a hand. We can schedule a quick call to go over the job together.

**Comment by tractorcow** [comment]
A simple straight replacement is substitute `extends Object` with `extends ViewableData` if you want a shortcut. ;)

**Comment by sminnee** [comment]
> A simple straight replacement is substitute extends Object with extends ViewableData if you want a shortcut. ;)

This would quite seriously change the meaning of your code. Adding the 3 traits would be much better.

```
    use Extensible;
    use Injectable;
    use Configurable;
```

**Comment by dhensby** [comment]
@TomasVotruba awesome; so how do we integrate this with our tool so we don't have to ask people to install 2 tools to upgrade their code; it'd be nice to just have a passthrough to rector.

Is there any nice way to extend or add commands to rector? Maybe we could do something like map our own internal rules to rector and call the rector internals via our tool?

**Comment by TomasVotruba** [comment]
@dhensby There are 2 paths to do this.

One is to register Rector services as your own, maintain compatibilites and basically  take care of each new BC break that happens. I needed something similar (and you might too) with coding standard tool. I needed to run rector bin file with `--with-style` optino to invoke conding standard tool. I could do the same as above - register coding standard services as my own, maintain compatibility etc.

But after few hours I relaized it's a waste of time :wastebasket: 

<br>

So instead I used thin intergrace via console option and Symfony\Process component:
https://github.com/rectorphp/rector/commit/5154cc81ec9f1939ba414a97f86b1515f5605be6

Easy to use, to maintain and to extend or switch if needed :rocket: 

<br>

What do you think?
