### ISSUE TITLE
Move command docs into README

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-upgrader#81]
We're forcing devs to click on a dozen links to get an impression what this thing actually does, just to show them half a screen page of information for each command. The `docs/` folder should be used to structure large documentation repositories, not as a means to break up every chapter/section into another click.

**Comment by maxime-rainville** [comment]
How about we add a small one sentence descriptions to each command on the main readme? eg,:
* [`environment`](#) migrates your `_ss_environment.php` file to a `.env`.

That way people can get a good overview of what each command does and click through for more details.

To some degrees, there's not much point in having detailed individual command doc as MD files, because each command is self-documented through the Symfony Console API. It might be more useful to move most of that doc to the commands and just give installation instructions.

**Comment by chillu** [comment]
> To some degrees, there's not much point in having detailed individual command doc as MD files

Even more of a reason to keep it simple and use one README. None of the current detail docs pages is more than half a screen of content, I struggle to see how that's easier to consume than a longer README.

**Comment by maxime-rainville** [comment]
I meant that the actual doc we provide in the repo is more detailed than the doc we provide in the self documented commands. So it would make some sense to copy some of that content in the actual commands.

For reference, that's the last version of the [ReadMe where we had all the commands in](https://github.com/silverstripe/silverstripe-upgrader/blob/851d46d69ac6bf51cc8ef8b4910fda6b965ba548/README.md). We've added a few commands since then.

If we bring all the docs for all the commands back in a single file, than we should include a TOC at the top so people can quickly find what they are looking for.

**Comment by chillu** [comment]
Yeah, ToC is a no brainer. Agree that some of this info will be useful as command documentation on CLI. I'll leave it up to you to find a good balance there
